name: gravitational_waves
description: This is a simple homage to Gravity Square, an old infinity runner discontinued by Kongregate.
version: 0.4.0
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: 1.0.0
  flame_audio: 1.0.0
  json_annotation: 4.3.0
  flame_splash_screen: 0.1.0
  shared_preferences: 2.0.9
  dio: 4.0.3
  url_launcher: 6.0.15
  google_mobile_ads: 1.0.0
  oktoast: 3.1.5
  firebase_core: 1.10.0
  firebase_analytics: 8.3.4
  dartlin: 0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flame_lint: 0.0.1
  build_runner: 2.1.5
  json_serializable: 6.0.1
  dashbook: 0.1.5
  flutter_launcher_icons: 0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/icon_background.png"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"

flutter:
  uses-material-design: true
  assets:
   - assets/firescore_uuid
   - assets/images/
   - assets/audio/music/
   - assets/audio/sfx/

  fonts:
   - family: Quantum
     fonts:
       - asset: assets/fonts/Quantum.otf

